apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unified-deployment
  namespace: argocd # ArgoCD's namespace
spec:
  project: default
  source:
    repoURL: "https://github.com/RajatSomani13/learn-devops.git" # Replace with your repo URL
    path: "argocd-applicationset" # Path to your ApplicationSet definition
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc" # Kubernetes API server
    namespace: argocd # ArgoCD's namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
