# argocd/argocd-unified-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: unified-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - chart: external-secrets
            name: external-secrets
            revision: 0.9.11
            namespace: external-secrets
            valuesFile: cluster-services/eso/values.yaml
          - chart: cloudnativepg
            name: cloudnativepg
            namespace: ds
            revision: 0.18.0
            valuesFile: datasource/postgres/values.yaml

  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace | default "default"}}'
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{ .repo }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .revision }}'
          helm:
            valueFiles:
              - '{{ .valuesFile }}'
        - repoURL: https://github.com/RajatSomani13/learn-devops.git
          targetRevision: HEAD
          ref: values
