apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnativepg-cluster
  namespace: ds
spec:
  instances: 3 # Number of PostgreSQL instances
  postgresql:
    parameters:
      max_worker_processes: "60"
    pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      - host all all all md5
    users:
      - name: admin
        superuser: true
        secretName: cloudnativepg-secrets
        secretKey: POSTGRES_USER
    passwordSecretName: cloudnativepg-secrets
    passwordSecretKey: POSTGRES_PASSWORD
  persistence:
    size: 10Gi # Persistent volume size
