apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnativepg-secrets
  namespace: ds
spec:
  backendType: secretsManager
  data:
    - key: POSTGRES_USER_KEY # Replace with Secrets Manager key
      name: POSTGRES_USER
    - key: POSTGRES_PASSWORD_KEY # Replace with Secrets Manager key
      name: POSTGRES_PASSWORD
  secretStoreRef:
    name: aws-secrets-store
  target:
    name: cloudnativepg-secrets
